project:
  type: book
  output-dir: docs

book:
  title: "Oficina: Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros"
  author: ""
  date: ""
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - metodologia.qmd
    - resultados.qmd
    - references.qmd

bibliography: 1_UFABC-TNC.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


