project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - apresentacao.qmd
    - Introducao.qmd
    - Objetivo_produtos.qmd
    - Atividades_oficinas.qmd
    - Glossario.qmd
    - Modelo_conceitual_premissas.qmd
    - Metodologia_resumida.qmd
    - Codigos_bases_dados.qmd
    - Diversidade_da_paisagem.qmd
    - Conectividade_local.qmd
    - Resiliencia_da_paisagem.qmd
    - Resultados.qmd
    - references.qmd
website: 
  navbar:
    left:
      - text: Tutoriais
        menu:
         - text: Diversidade da paisagem
         - text: Resistência da paisagem
         - text: Conectividade local 
         - text: Resiliência da paisagem  
      - text: Downloads
        href: https://projeto-resiliencia-tnc.hub.arcgis.com        
  sidebar: 
    title: "Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros" 
    logo: figs/1667403883848_theme_logo.png     
    style: "docked"
    contents:
      - section: "Sumário"
        contents:
          - index.qmd
          - apresentacao.qmd
          - Introducao.qmd
          - Objetivo_produtos.qmd
          - Atividades_oficinas.qmd
          - Glossario.qmd
          - Modelo_conceitual_premissas.qmd
          - Metodologia_resumida.qmd
          - Codigos_bases_dados.qmd
          - Diversidade_da_paisagem.qmd
          - Conectividade_local.qmd
          - Resiliencia_da_paisagem.qmd
          - Resultados.qmd
          - references.qmd          
  page-navigation: true
  favicon: figs/1667403883848_theme_logo.png
bibliography: bibliografia.bib
csl: citation_style.csl
lang: pt-br
format:
  html:
    theme: default
    css: styles.css   

