project:
  type: book
  output-dir: docs
logo: figs/TNC.jpg
book:
  title: "Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros"
  author: ""
  date: ""
  chapters:
    - index.qmd
    - Introducao.qmd
    - Equipe_envolvida.qmd
    - Objetivo_produtos.qmd
    - Atividades_oficinas.qmd
    - Glossario.qmd
    - Modelo_conceitual_premissas.qmd
    - Metodologia_resumida.qmd
    - Codigos_bases_dados.qmd
    - Diversidade_da_paisagem.qmd
    - Conectividade_local.qmd
    - Resiliencia_da_paisagem.qmd
    - Resultados.qmd
    - references.qmd
  page-navigation: true
  favicon: figs/TNC.png
bibliography: bibliografia.bib
csl: citation_style.csl
lang: pt-br
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    reference-doc: custom-reference.docx  


