project:
  type: book
  output-dir: docs
logo: figs/TNC.jpg
book:
  title: "Oficina: Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros"
  author: ""
  date: "2023-06-12"
  chapters:
    - index.qmd
    - intro.qmd
    - objetivo.qmd
    - metodologia.qmd
    - implementacao.qmd
    - resultados.qmd
    - oficina.qmd
    - references.qmd
  page-navigation: true
  favicon: figs/TNC.png
bibliography: bibliografia.bib
csl: citation_style.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    reference-doc: custom-reference.docx  


