project:
  type: book
  output-dir: docs

book:
  title: "Oficina: Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros"
  author: ""
  date: ""
  chapters:
    - index.qmd
    - summary.qmd
    - justificativa.qmd
    - objetivo.qmd
    - intro.qmd
    - metodologia.qmd
    - implementacao.qmd
    - resultados.qmd
    - references.qmd

bibliography: bibliografia.bib
csl: citation_style.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


