# Aplicações

Com os resultados obtidos e as bases geradas no estudo de identificação de paisagens resilientes às mudanças climáticas é possível apoiar a formulação de políticas públicas de conservação, restauração e uso sustentável dos recursos naturais em diferentes escalas espaciais. A base de informações gerada pode ser útil para o planejamento na esfera nacional, por bioma e mesmo em recortes espaciais menores como estados, bacias e outras unidades espaciais. Esses resultados poderão ainda ser avaliados nestas distintas escalas para entendermos melhor as vantagens e limites de seu uso. Essas bases podem também ser úteis em pesquisas ecológicas e de conservação visando compreender os efeitos dos diferentes componentes da paisagem (heterogeneidade do relevo, conectividade e resiliência) sobre espécies focais, guildas e comunidades.

Um outro ponto importante é a consideração de como essas bases podem ser úteis para apontar áreas importantes para a restauração, uma vez que a resiliência às mudanças climáticas raramente é um critério utilizado na busca destas áreas. A importância da restauração ativa e passiva é hoje uma prioridade global amplamente reconhecida e estes resultados podem indicar, junto com outras informações, áreas onde podemos otimizar nossos esforços de conservação frente às mudanças climáticas.

As áreas de maior resiliência (áreas em verde no mapa de resiliência) são aquelas com maior potencial para conservação no futuro, pois, indicam locais com maior heterogeneidade da paisagem e conectividade local e que oferecem melhores condições para que organismos e espécies tenham habitats mais diversos, favorecendo sua persistência frente às mudanças climáticas futuras (Figura 28 e Figura 31).

Locais com alta conectividade local, mas baixa heterogeneidade da paisagem (áreas em amarelo no mapa de resiliência), embora não apresentem resiliência elevada, apresentam baixa resistência e vegetação natural mais preservada, e podem ser importantes para conservação, pois têm potencial de permitir o deslocamento e fluxo de indivíduos na paisagem. Ou seja, são locais que funcionam para facilitar o fluxo da biodiversidade, servindo como potenciais corredores ecológicos.

Por outro lado, locais com alta heterogeneidade da paisagem, mas baixa conectividade local (áreas em azul no mapa de resiliência), embora não apresentem resiliência elevada, são locais com alto potencial de aumento da resiliência, tão logo a vegetação nativa seja recuperada. Nesses locais, ações de restauração podem propiciar o restabelecimento da vegetação nativa, aumentando assim a conectividade entre fragmentos e aumentando a resiliência da paisagem. Assim, corredores ecológicos entre áreas naturais devem ser estabelecidos ou preservados a fim de promover o fluxo da biodiversidade.

Por fim, locais com baixa resiliência (áreas em cinza no mapa de resiliência), que são aqueles mapeados com baixa heterogeneidade da paisagem e baixa conectividade local, apresentam baixo potencial para aumento da resiliência. Esses locais poderiam ser focados para uso mais sustentável da terra e provisão de serviços ambientais, gerando regiões com menor resistência da paisagem e que oferecem menor impacto para a biodiversidade.

[INSERIR FIGURA 31]
Figura 31.  Exemplo da classificação de resiliência da paisagem e divisões dos quadrantes da escala bivariada de cores, focando na região circundante do Parque Indígena do Xingu e Parque Nacional do Araguaia. A) Visualização das áreas classificadas no primeiro quadrante (Q1) da escala bivariada, com baixa heterogeneidade da paisagem e baixa conectividade local; B) Visualização das áreas classificadas no segundo quadrante (Q2) da escala bivariada, com alta heterogeneidade da paisagem, mas baixa conectividade local; C) Visualização das áreas classificadas no terceiro quadrante (Q3) da escala bivariada, com baixa heterogeneidade da paisagem e alta conectividade local. D) Visualização das áreas classificadas no quarto quadrante (Q4) da escala bivariada, com alta heterogeneidade da paisagem e alta conectividade local.

Uma outra questão importante que pode ser abordada com base em nossos resultados é a efetividade de conservação das áreas protegidas (unidades de conservação e territórios indígenas) atuais considerando o impacto das mudanças climáticas na biodiversidade. É possível identificar áreas potenciais para restauração de modo a aumentar a resiliência da paisagem e promover a conexão entre áreas resilientes e conservadas, bem como identificar possíveis corredores resilientes entre áreas protegidas. Estratégias de restauração podem ser adotadas para aumentar a conectividade em locais que propiciem, no gráfico de resiliência da paisagem (Figura 32), a mudança de situação entre as classes da esquerda para a direita: por exemplo, direcionando ações em locais indicados como classe 14 para que no futuro eles mudem para a classe 24 (o mesmo vale para as classes de 24 para a 34, ou de 34 para 44).

[INSERIR FIGURA 32]
Figura 32. Resiliência da paisagem, resultante do cruzamento dos mapas de heterogeneidade da paisagem e conectividade local, classificados por quantis de 25%. A classificação bivariada da camada de resiliência da paisagem foi dividida em quadrantes com diferentes graus de conectividade local e heterogeneidade da paisagem e sobrepostas com as delimitações de Terras Indígenas (em vermelho) e Unidades de Conservação (em violeta).

