# Considerações finais

O mapeamento de áreas de resilientes apresentado neste trabalho busca identificar locais com maior variabilidade microclimática e conectadas utilizando a abordagem chamada de conservando o palco da natureza (do inglês, *conserving nature's stage*). Dessa forma, identificamos locais e regiões com potencial de apresentar maior variabilidade microclimática e conectividade na paisagem, consequentemente oferecendo refúgios microclimáticos dada as suas características topográficas, hidrológicas e edáficas.

Um ponto importante sobre o mapeamento é que ele se refere a ambientes terrestres, sem considerar variáveis importantes para ambientes aquáticos tanto na análise de heterogeneidade da paisagem quanto na de conectividade local. Por exemplo, na análise apresentada, os diferentes valores de resistência propostos para os corpos d’água, com base na sua largura, tiveram como referência o grau de dificuldade que oferecem a organismos terrestres em seu deslocamento na paisagem. Portanto, não são apresentados resultados de resiliência para corpos d'água e ecossistemas aquáticos.

Uma vez que o relevo tende a mudar pouco ou lentamente com o tempo, consideramos que áreas com maior variação de formas de relevo deverão ser mais resilientes às mudanças climáticas previstas. Apesar do impacto local das mudanças climáticas ser definido pela interação entre atmosfera, biodiversidade e a diversidade do meio físico, a última variável não tem sido considerada. Dessa forma, o nosso mapeamento não substitui as abordagens climáticas e ecossistêmicas, mas complementa e proporciona uma nova faceta para a identificação de localidades potencialmente resilientes a mudanças climáticas, principalmente no nível local, onde dados microclimáticos são escassos.

É importante ressaltar que, nos cálculos de conectividade local, utilizamos as diferenças estruturais dos vários tipos de uso e cobertura do solo como *proxies* da resistência, sendo as áreas naturais menos resistentes e as áreas antropizadas mais resistentes ao deslocamento de organismos na paisagem. Embora os valores de resistência tenham variado em função do bioma analisado, variações nas percepções das diferentes espécies e grupos de organismos não foram consideradas.

Uma vez que os tutoriais de análise foram disponibilizados como produtos desse projeto, aplicações futuras focadas em grupos específicos de organismos podem ser realizadas, necessitando apenas adequar os valores de resistência para cada classe de uso e cobertura do solo e recalcular a camada de conectividade local de acordo com a biologia e mobilidade da espécie alvo. Com a nova camada de conectividade local, deve-se cruzar com a camada de heterogeneidade da paisagem para gerar uma nova camada de resiliência da paisagem adequada para o organismo de interesse.

Esperamos que nosso trabalho contribua para o desenvolvimento de metodologias multi-escala sobre o impacto das mudanças climáticas na biodiversidade. Dessa forma, nossos resultados permitem o refinamento da resiliência em escalas locais quando identificados locais com baixa mudança climática regional. Ao combinarmos essas informações com a modelagem das mudanças estruturais e funcionais nos ecossistemas conseguiremos compreender melhor o impacto das mudanças atuais na biodiversidade e como mitigá-las. 

