# Diversidade da paisagem

A diversidade da paisagem é uma métrica composta pelas médias de *Z-scores* da [__variedade de landforms__](#variedade-de-landforms), [__amplitude altitudinal__](#amplitude-altitudinal), [__índice de áreas úmidas__](#índice-de-áreas-úmidas) e [__diversidade de solo__](#diversidade-de-solo). A composição da métrica possui uma hierarquia entre as variáveis para o cálculo das médias **(Figura)**. A seguir, descreveremos como cada variável que compõe a métrica é criada e como elas são combinadas para formar a diversidade da paisagem. 
As análises de diversidade da paisagem foram realizadas no *Google Earth Engine* [@gorelick_google_2017] devido a demanda computacional, sua escalabilidade, a possibilidade de reprodução das análises e transparência.

#### Variedade de _landforms_ {-}

A variedade de landforms é a quantidade de formas de relevo dentro de uma vizinhança da célula focal. Primeiro classificamos as formas de relevo e em seguida contabilizamos a quantidade de formas no entorno de cada célula.

##### Classificação das *landforms*

As formas de relevo representam a variação na umidade, exposição à radiação solar, velocidade de ventos e deposição de sedimentos na paisagem [@dobrowski_climatic_2011; @anderson_resilient_2016]. Essa classificação é determinada pelas variáveis de **declividade do relevo** (_slope_), **orientação do relevo** (_aspect_), **índice de posição topográfica** (_topographic position index_), **índice de umidade** (_moisture index_) e a distribuição de **rios** e **lagos**. A combinação dessas variáveis determinam os topos de montanhas e vales, áreas íngremes ou planas, orientação do relevo com mais sombra ou incidência solar, áreas secas ou úmidas dado o acúmulo de fluxo, declividade do relevo e a presença de lagos e rios (@fig-landforms). A classificação foi baseada em estudos anteriores [@fels_cognitively-based_1996; @anderson_resilient_2016; @anderson_resilient_2012;  @anderson_mark_g_estimating_2014; @anderson_mark_g_resilient_2023] para a América do Norte ( [https://crcs.tnc.org/pages/land](https://crcs.tnc.org/pages/land)). 


<!--Precisamos antes do produto final arrumar algumas citações manualmente, o zotero está bagunçando alguns nomes -->

Modificações foram feitas em relação aos estudos anteriores. O  cálculo da posição topográfica foi substituído entre o *landscape position index* (LPI) [@anderson_resilient_2012] por *topographic position index* [@weiss_topographic_2001]. A orientação do relevo (faces quentes ou frias) foi ajustada para o Hemisférios Sul. A classificação das *landforms* foi ajustada para valores das variáveis que melhor classificavam as formas de relevo das paisagens analisadas.

![Classificação de *landforms* de acordo com a declividade do relevo, índice de posição topográfica,
  orientação do relevo, índice úmidade, rios e lagos. Baseado na classificação de @anderson_resilient_2016.](figs/landform_scheme.png){#fig-landforms}

  
  
Para o cálculo de [inclinação](#inclinação-do-relevo), [orientação do relevo](#orientação-do-relevo) e [índice de posição topográfica (TPI)](#índice-de-posição-topográfica), utilizamos o modelo digital de elevação (DEM) do Merit-DEM [@yamazaki_high-accuracy_2017], em uma escala de 90 m. Escolhemos utilizar esse DEM por ser um produto em escala global, de livre acesso e com correções de vários viéses de modelos de elevação, principalmente viéses de elevação em áreas com alta densidade de florestas. Além disso, o Merit-DEM já possui um [acúmulo de fluxo](#acúmulo-de-fluxo) calculado sobre ele, em escala global, disponível no Merit-Hydro [@yamazaki_merit_2019]. Essa camada de acúmulo de fluxo é corrigida para o efeito da densidade de árvores no cálculo da rede hidrográfica da região [@yamazaki_merit_2019], o que possibilita que nosso trabalho seja replicável e mais próximo da realidade dos biomas que modelamos.

Para complementar a superfície gerada pelo acúmulo de fluxo e definir a presença de **rios** e **lagos** <!--e **áreas umidas** -->, nós incluímos as classes de água do MapBiomas Coleção 7 [@mapbiomas_project_collection_2020]. O MapBiomas é um projeto nacional de mapeamento e classificação de mudanças do uso do solo dos últimos 30 anos, a partir de dados de sensoriamento remoto.


##### Índice de posição topográfica (TPI) {-}

O cálculo do TPI foi feito em três escalas com uma janela circular com 7, 11 e 15 células de raio, calculando a diferença da média de elevação entre a célula focal e um conjunto de células vizinhas ($i$), divididos pelo número de células vizinhas ($n$).

$$
TPI = \frac {\sum  _{i}^{n}\left(vizinhança_i - focal \right)}{n}
$$

O índice é composto pela média de TPI das três escalas, o que permite a consideração de níveis locais e regional de resolução da paisagem [@theobald_ecologically-relevant_2015]. Os tamanhos das janelas foram definidos visualmente para que melhor representassem as formas de relevo.

##### Orientação do relevo (*aspect*) {-}
A orientação do relevo é calculado como um gradiente local das 4 células adjacentes. Os resultados são apresentados em graus, que representam a direção do relevo (0º = Norte, 90º = Leste, 180º = Sul e 270º = Oeste). Nós dividimos a orientação do relevo em dois grupos, baseados na quantidade de incidência solar, sendo células com valores entre 90º e 270º classificados como **faces frias** e valores entre 0º a 90º e 270º a 360º, classificados como **faces quentes**.

##### Inclinação do relevo (*slope*) {-}
A inclinação do relevo é calculada como um gradiente local das 4 células adjacentes, os resultados são apresentado em graus que representam a inclinação do relevo (0º a 90º). 

<!-- A inclinação foi dividida em 5 grupos baseado em faixas de inclinação, para melhor classificar diferentes formas do relevo (@tbl-inclinacao).

|Inclinação|Grupo|
|--:|--:|
|0º a 2º  | 1 |
|2º a 6º  | 2 |
|6º a 24º | 3 |
|24º a 35º| 4 |
|35º a 90º| 5 |
: Classes de declividade usadas para a classificação de _landforms_ {#tbl-inclinacao}
-->

##### Índice de umidade (*moisture index*) {-}
O índice de umidade (_moisture index_) foi calculado com base no **acúmulo de fluxo** do Merit-Hydro e a **inclinação do relevo** que calculamos anteriormente.
$$
moisture.index = \frac{\log \left(fluxo+1\right)}{\left(slope+1\right)}  \times1000
$$
O índice de umidade é a média do índice dentro de uma janela circular de uma célula de raio determinado. O tamanho do raio foi escolhido visualmente para suavizar o índice, mas representando bem a distribuição dos cursos d'água.

<!--
Classificamos como áreas úmidas somente regiões que apresentassem um valor do índice de umidade acima de 3000 e definimos esse valor para que visualmente pudéssemos capturar a distribuição dos cursos d'água sem superestimar outras áreas planas. Porém, esse corte do índice não consegue classificar bem corpos de água com grandes extensões (por exemplo, rio Amazonas, represas e grandes lagos), por isso nós corrigimos a classificação sobrepondo a camada do índice de umidade com a camada de águas do MapBiomas.
-->
#### Transformando os índices em classes {-}

Cada índice (TPI, inclinação, orientação e índice de úmidade) foi transformado em classes (@tbl-classes) para formarem os tipos de *landforms*. O índice umidade é classificado como presença ou ausência de umidade, sendo locais com rios e lagos classificados como presença.  

| Variáveis | Classes | Limiar inferior | Limiar superior |
|:-:|:-:|:-:|:-:|
| Inclinação do relevo|1|-1|2|
|Inclinação do relevo|2|2|6|
|Inclinação do relevo|3|6|24|
|Inclinação do relevo|4|24|35|
|Inclinação do relevo|5|35|90|
|TPI|1|-Inf|-15|
|TPI|2|-15|-1|
|TPI|3|-1|30|
|TPI|4|30|975|
|Aspecto|2|0|90|
|Aspecto|1|90|270|
|Aspecto|2|270|360|
|Índice de Umidade|0|-Inf|30000|
|Índice de Umidade|1|3000|Inf|
: Classes dos índices usados para a classificação de _landforms_ {#tbl-classes}

##### Combinando as variáveis e classificando as _landforms_ {-}

A partir das classificações de todas as variáveis, geramos um código representativo das combinações de classificações das localidades. A classe do índices de umidade é multiĺicado por 1000, orientação do relevo por 100, TPI por 10 e inclinação do relevo por 1. Dessa forma, podemos representar as classes dos índices de uma localidade por um único número. Por exemplo, o código 11 representa áreas de baixa inclinação do relevo e uma posição do relevo mais alta que o entorno, sendo portanto um topo de montanha (_summit_). No entanto, alguns códigos tiveram que ser inspecionados visualmente para classificar alguns tipos de _landforms_, como _sideslopes_, _valleys_ e _toeslopes_ (@tbl-combinacoes).

|Valores da Combinação| Código para Landforms|
|--:|--:|
|10| 11|
|11| 11|
|12| 11|
|13| 13|
|14| 11|
|15| 5|
|20| 21|
|21| 21|
|22| 22|
|23| 24|
|24| 24|
|25| 5|
|31| 30|
|32| 32|
|33| 24|
|34| 24|
|35| 5|
|40| 32|
|41| 32|
|42| 32|
|43| 43|
|44| 3|
|45| 5|
|51| 51|
|111| 11|
|112| 11|
|113| 13|
|114| 3|
|115| 5|
|121| 21|
|122| 22|
|123| 23|
|124| 3|
|125| 5|
|131| 30|
|132| 32|
|133| 23|
|134| 3|
|135| 5|
|141| 32|
|142| 32|
|143| 43|
|144| 3|
|145| 5|
|151| 51|
|211| 11|
|212| 11|
|213| 13|
|214| 4|
|215| 5|
|221| 21|
|222| 22|
|223| 24|
|224| 4|
|225| 5|
|231| 30|
|232| 32|
|233| 24|
|234| 4|
|235| 5|
|241| 32|
|242| 32|
|243| 44|
|244| 4|
|245| 5|
|251| 51|
|1000| 39|
:Combinações entre as variáveis para classificar as formas de relevo {#tbl-combinacoes}

A classificação final de landforms se encontra na @tbl-landforms.

|Códigos | Nomes|
|--:|--:|
|3 |Cool Steep Slope  |
|4 | Warms Steep Slope  |
|5 |Cliff  |
|11 | Summit/Ridgetop  |
|13 | Slope Crest  |
|21 | Flat Hilltop  |
|22 | Gentle Slope Hilltop|
|23 | Cool Sideslope  |
|24 | Warm Sideslope  |
|30 | Dry Flats  |
|32 | Valley/Toeslope|
|39 | Moist Flats  |
|43 | Cool Footslope  |
|44 |Warm Sideslope|
: Códigos das formas de relevo obtidas após classificação das variáveis {#tbl-landforms}

<!-- Seria interessante algumas figuras de exemplos de landforms dentro dos biomas!!-->

##### Gerando a variedade de _landforms_ {-}
A variedade de _landforms_ foi calculada como quantidade de tipos de _landforms_ dentro de um _kernel_ circular da célula focal. O tamanho do raio do kernel foi definido calculando a variedade em diferentes raios (2, 5, 7, 10, 15, 20 células) e calculando o ganho de variedade a cada aumento de raio. O raio escolhido foi aquele em que o seu subsequente não adicionou variedade. 

Desta forma, o raio representa o nível de resolução da paisagem que captura o máximo de variedade de landforms. <!-- Raios maiores podem aumentar a variedade, mas devido a mudança de paisagem. --> Assim, o raio escolhido foi de 5 células de raio (450 m) para todo o Brasil.
Por fim, calculamos os valores de Z para cada pixel ($Z_{pixel}$) ao subtrair o valor da média ($\mu$) e dividindo o resultado pelo desvio padrão ($\sigma$), como mostrado na fórmula a seguir:
$$
Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}
$$
Os cálculos de $Z$ foram feitos dentro de cada classificação de **regiões eco-geológicas** usando médias e desvios padrão dentro de cada uma das classes.

#### Amplitude altitudinal {-}

A amplitude altitudinal representa a variação da elevação em uma região, independente do número de [___landforms___](#variedade-de-landforms), controlando a relação entre ambas já que elas são correlacionadas entre si. A amplitude altitudinal foi calculada como a diferença entre os valores máximos e mínimos de elevação, dentro de um _kernel_ circular de 450 m, a partir dos dados do DEM do MERIT [@yamazaki_high-accuracy_2017]. fizemos então uma Regressão Linear Simples (_Ordinary Linear Regression_) entre os **valores de amplitude altitudinal** e a **variedade _landforms_** e obtivemos os valores dos resíduos dessa análise para diminuir a correlação estre as duas variáveis.

Por fim, os valores da variação desses resíduos da correlação entre a amplitude e a variedade da forma de relevo, para cada pixel ($Z_{pixel}$), podem ser calculados ao subtrair o valor da média ($\mu$) e dividir o resultado pelo desvio padrão ($\sigma$), como mostrado na fórmula a seguir:
$$Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}$$

Dessa forma, temos uma imagem que mostra a variação, em relação à média, dos valores dos resíduos da amplitude altitudinal dentro de cada uma das categorias de regiões eco-geológicas.

#### Índice de áreas úmidas {-}

Para calcular o índice de áreas úmidas, utilizamos os dados disponibilizados na base de dados _Global Wetlands Database_ [@gumbricht_tropical_2017], que é uma base de dados que fornece informação e inventário de áreas úmidas no mundo. Os dados são obtidos através de imagens de satélite, amostragens aéreas e relatórios publicados. Como áreas úmidas ocorrem em diversas configurações e distribuições no espaço, nós avaliamos a densidade e o número de áreas úmidas em escala local (450 metros) e escala regional (1170 metros).
A **densidade de áreas úmidas** foi calculada como a média do número de _pixels_  de áreas úmidas, dentro de um _kernel_ de escala regional (1170 m) e um kernel em escala local (450 m).
Já a **contagem em escala local** foi calculada como uma contagem de _pixels_ dentro de um _kernel_ circular em escala regional (1170 metros). A contagem vai representar o número de áreas umidas ao redor do _pixel_ focal, mostrando regiões de maiores quantidades de áreas úmidas, mas em baixa densidade.

Essas 3 camadas vão auxiliar na identificação de regiões de diversidade da paisagem que apresentem valores baixos para formas de relevo e amplitude de elevação, mas que tenham um acúmulo de áreas umidas que poderiam amenizar localmente o efeito das mudanças climáticas [@anderson_resilient_2016].

Para calcular os **valores finais de áreas úmidas**, é necessário juntar as informações das camadas de **densidade local**, **densidade regional** e a **contagem em escala local**. Começamos calculando valores padronizados para cada uma delas ($Z_{local}$, $Z_{regional}$ e $Z_{contagem}$, respectivamente)  ao subtrair os valores de pixels ($X_{pixel}$) pela média ($\mu$) e dividirmos o resultado pelo desvio padrão ($\sigma$) dentro das diferentes categorias de [__regiões eco-geológicas__](#regiões-eco-geológicas), como na fórmula:
$$
Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}
$$

Com o $Z$ calculado para as 3 camadas, podemos calcular os valores de áreas úmidas ($Z_{úmidas}$) ao fazermos uma média dos valores para as camadas de densidade local, densidade regional e contagem.

Primeiro calculamos a média entre as imagens de valores de áreas úmidas em escala local ($Z_{local}$) e regional ($Z_{regional}$), atribuindo mais peso para os valores da densidade local:
$$
Z_{densidade}=\frac {{{(Z_{local}}{\times2)}}+{Z_{regional}}}{3}
$$
Ao compararmos esse resultado com a camada de contagem regional, podemos identificar os locais onde os valores para densidade ($Z_{densidade}$) são menores que os valores de contagem ($Z_{contagem}$) e calculamos a média para esses pixels, novamente dando mais peso ao valores de densidade:

$$
Z_{úmidas}=\frac {{{(Z_{densidade}}{\times3)}}+{Z_{contagem}}}{4}
$$
Ao final de todas as operações, temos uma única camada com valores que representam a variação em relação à média dos valores de densidade e contagem de pixels de áreas úmidas referentes às regiões eco-geológicas.

#### Diversidade de solo {-}

A diversidade de solo foi calculada como a distribuição do número de classes de solo, dentro de um _kernel_ de 1350 m. Ela foi usada para indicar áreas com grande concentração dos diferentes tipos de solo que vão afetar diretamente na diversidade de espécies no ambiente. Para calcular o raster de diversidade do solo usamos a classificação oficial dos solos brasileiros, disponibilizada pelo [Instituto Brasileiro de Geografica e Estatística (IBGE)](https://www.ibge.gov.br/geociencias/informacoes-ambientais/pedologia/10871-pedologia.html).

Como a classificação do IBGE foi disponibilizada em formato de _shapefile_, começamos a análise separando cada uma das 108 classes de solo do Brasil e calculamos um raster de presença e ausência do tipo de solo. Ao final do processo podemos somar os diferentes mapas de presença para obter os mapas de diversidade do solo, onde os maiores valores de cada pixel mostram áreas com concentração de diferentes tipos de solo.

Por fim, calculamos os valores de Z para cada pixel ($Z_{pixel}$) ao subtrair o valor da média ($\mu$) e dividindo o resultado pelo desvio padrão ($\sigma$), como mostrado na fórmula a seguir:
$$Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}$$
Os cálculos de $Z$ foram feitos dentro de cada classificação de regiões eco-geológicas usando as médias e desvios padrão dentro de cada uma das classes.

#### Diversidade da paisagem {-}
A diversidade da paisagem é calculada pela média dos maiores valores de $Z$ entre **variedades de landforms** ($Z_{diversidade}$), **amplitude de elevação** ($Z_{elevação}$), **índice de áreas úmidas** ($Z_{úmidas}$) e **diversidade de solo** ($Z_{solos}$). Começamos assumindo que a diversidade da paisagem seja igual a variedade de _landforms_ nos locais onde os valores de amplitude de elevação sejam maiores que a variedade de _landforms_ a diversidade da paisagem é calculada como a média entre os valores de $Z$ das duas camadas, com maior peso dado para a camada de variedade de landforms, conforme a fórmula a seguir.
$$
Z_{diversidade}= \frac{\left(Z_{landforms}\times 2 \right)+Z_{elevação}}{3}
$$
Depois comparamos os valores desse $Z$ com a camada do índice de áreas úmidas e nas áreas onde esses valores sejam maiores substituímos pelo valor do índice de áreas úmidas. Portanto em regiões onde os valores de áreas úmidas são maiores eles substituem os valores de $Z$ nesses _pixels_.

Na localidades onde a diversidade de solo é maior que a diversidade da paisagem, os valores são substituídos pela média ponderada das variáveis naquela localidade
Nas localidades onde a diversidade do solo for maior que a diversidade da paisagem calculada até aqui, vamos substituir os valores pela média ponderada entre todas as outras camadas, dependendo de quais camadas apresentam maiores valores.

Se os valores da diversidade forem menores que os valores de _landforms_, amplitude de elevação, índice de áreas úmidas e diversidade de solo somamos todos os valores de $Z$, dobrando os valores de _landforms_ e dividimos por 5.
$$
Z_{diversidade}= \frac{\left(Z_{landforms}\times 2 \right)+Z_{elevação}+Z_{úmidas}+Z_{solos}}{5}
$$


Se os valores de diversidade forem menores que variedade de _landforms_ elevação e diversidade de solos, mas forem maiores que o índice de áreas úmidas somamos os valores das 3 camadas, dobrando os valores para _landforms_ e dividimos por 4.
$$
Z_{diversidade}= \frac{\left(Z_{landforms}\times 2 \right)+Z_{elevação}+Z_{solos}}{4}
$$
Se os valores de diversidade forem menos que _landforms_, índices de áreas úmidas e amplitude de elevação, somamos os valores das 3 camadas, dobrando os valores de _landforms_ e dividimos por 4.
$$
Z_{diversidade}= \frac{\left(Z_{landforms}\times 2 \right)+Z_{elevação}+Z_{úmidas}}{4}
$$

Se os valores de diversidade forem menores que variedade de _landforms_ e diversidade de solo, somamos os valores das camadas, dobrando os valores de _landforms_ e dividimos por 3.

$$
Z_{diversidade}= \frac{\left(Z_{landforms}\times 2 \right)+Z_{solos}}{3}
$$
Agora os valores de diversidade de paisagem já contém toda a variação das camadas de $Z$ que calculamos anteriormente, como temos uma grande variação dos valores fazemos um truncamento dos valores da diversidade maiores e menores que 95% da distribuição dos dados. Esse truncamento foi feito para suavizar a imagem final de diversidade e remover valores _outliers_ que possam influenciar o cálculo da [__Resiliência da Paisagem__](#resiliência-combinando-diversidade-da-paisagem-e-conectividade-local). Para essa suavização, calculamos a distribuição dos dados e todo valor de _pixel_ fora de 95% da distribuição foi substituido pelos valores de máximo e mínimo da distribuição. 
