# Glossário

## Resiliência da paisagem (_landscape resilience_)
Capacidade de uma área de absorver impactos das mudanças climáticas na diversidade de espécies e funções ecológicas. Uma área resiliente apresenta variabilidade de condições que sustentam a biodiversidade, mantendo relações fundamentais entre componentes ecológicos, e permite mudança adaptativa na composição de espécies e estrutura do ecossistema

## Heterogeneidade da paisagem (_landscape heterogeneity_)
Estimativa da variabilidade de habitat e microclimas, definida pelas formas de relevo, amplitude altitudinal, índice de áreas úmidas e riqueza de solos presentes no entorno de uma dada localidade.

## Resistência da paisagem (_landscape resistance_)
Dificuldade imposta pelas classes de uso e cobertura do solo à movimentação dos organismos.

## Conectividade local (_local connectedness_)
Medida de facilitação ao deslocamento de organismos entre os elementos da paisagem (ou tipos de uso e cobertura do solo). A conectividade é influenciada tanto pela resistência dos elementos da paisagem ao deslocamento dos organismos, quanto pelo arranjo espacial desses elementos.

## Paisagem (_landscape_)
Área espacialmente delimitada e que apresenta heterogeneidade para diferentes aspectos (formas de relevo, altitude, resistência e configuração espacial) capaz de influenciar os processos ecológicos em seu interior.

## Formas de relevo (_landforms_)
Feições topográficas presentes na paisagem, como topos de montanhas, vales e desfiladeiros. Cada feição topográfica sofre diferentes níveis de exposição à radiação solar, vento e umidade, sendo a variabilidade das formas de relevo usada como proxy dos microclimas da paisagem.

## Densidade de áreas úmidas (_wetland density_)
Quantidade de locais saturados de água, que ficam encharcados ou alagados de forma perene ou sazonal, presentes em uma determinada região.

## Padrão de distribuição regional de áreas úmidas (_wetland patchiness_)
Quantidade de áreas úmidas em uma determinada região.
