# Detalhamento das análises

O detalhamento das análises apresenta uma descrição mais aprofundada da metodologia utilizada para o mapeamento. São apresentadas as bases de dados e o diferentes critérios utilizados para desenvolver as análises, considerando as diversas camadas necessárias para gerar o mapa de resiliência da paisagem.

## Regiões eco-geológicas

As regiões eco-geológicas do Brasil foram delimitadas para encontrar regiões homólogas em relação aos **domínios geológicos** e às **ecoregiões** do país. Essas regiões são usadas para limitar a variação das características ambientais usadas ao calcular a [__Resiliência da Paisagem__](#resiliência-da-paisagem), de modo a normalizar os valores de resiliência de acordo com regiões homólogas, ao invés de todo o país.

Os **domínios geológicos** são grupos de unidades geológicas, separados pelas similidades nas classificações de tipo de rocha. Os domínios foram criados a partir da classificação feita pela CPRM (Serviços Geológico do Brasil). A classificação por unidades geológicas consistia em um número muito grande de categorias para o Brasil (aproximadamente 1350), por esse motivo utilizamos um agrupamento dessas categorias por domínios geológicos (14 domínios).

Já as **ecoregiões** são agrupamentos de regiões ecológicas similiares e consistem em unidades biogeográficas que compartilham comunidades naturais de espécies, dinâmicas naturais e condições ambientais [@olson_terrestrial_2017]. Nós utilizamos a classificação da Terrestrial Ecoregions of the World (TEOW), que é uma regionalização biogeográfica da biodiversidade terrestre realizada pela WWF, que classifica o Brasil em 50 ecoregiões.

Tanto os domínios geológicos quanto as ecoregiões são polígonos, que representam as diferentes categorias, que foram rasterizados para prosseguir com o cálculo das regiões eco-geológicas, através da sequinte equação:
$$Regiões\ eco-geológicas = {(Ecoregiões)+(100\times Domínio \ Geológico)}$$
Desta forma, os valores do raster final estão no formato **GGEE**, onde os duas primeiras unidades (**GG**) representam os domínios geológicos e as duas últimas (**EE**) as categorias de ecoregiões.
<!--
|Código|Ecoregião|
|1|Alto Paraná Atlantic forests|
|2|Amazon-Orinoco-Southern Caribbean mangroves|
|3|Araucaria moist forests|
|4|Atlantic Coast restingas|
|5|Atlantic dry forests|
|6|Bahia coastal forests|
|7|Bahia interior forests|
|8|Beni savanna|
|9|Caatinga|
|10|Caatinga Enclaves moist forests|
|11|Campos Rupestres montane savanna|
|12|Caqueta moist forests|
|13|Cerrado|
|14|Chiquitano dry forests|
|15|Dry Chaco|
|16|Espinal|
|17|Fernando de Noronha-Atol das Rocas moist forests|
|18|Guianan Highlands moist forests|
|19|Guianan moist forests|
|20|Guianan piedmont and lowland moist forests|
|21|Guianan savanna|
|22|Gurupa varzeá|
|23|Humid Chaco|
|24|Iquitos varzeá|
|25|Japurá-Solimoes-Negro moist forests|
|26|Juruá-Purus moist forests|
|27|Madeira-Tapajós moist forests|
|28|Marajó varzeá|
|29|Maranhão Babaçu forests|
|30|Mato Grosso seasonal forests|
|31|Monte Alegre varzeá|
|32|Negro-Branco moist forests|
|33|Northeastern Brazil restingas|
|34|Pantanal|
|35|Pantepui|
|36|Pernambuco coastal forests|
|37|Pernambuco interior forests|
|38|Purus varzeá|
|39|Purus-Madeira moist forests|
|40|Rio Negro campinarana|
|41|Serra do Mar coastal forests|
|42|Solimões-Japurá moist forests|
|43|Southern Atlantic mangroves|
|44|Southern Cone Mesopotamian savanna|
|45|Southwest Amazon moist forests|
|46|Tapajós-Xingu moist forests|
|47|Tocantins/Pindare moist forests|
|48|Uatuma-Trombetas moist forests|
|49|Uruguayan savanna|
|50|Xingu-Tocantins-Araguaia moist forests|
-->

## Resiliência da Paisagem
A resiliência da paisagem foi calculada como a média entre os valores padronizados (${Z}$) de [__diversidade da paisagem__](#diversidade-da-paisagem) e de [__conectividade local__](#conectividade-local). Todas as imagens utilizadas para o cálculo de resiliência estão na escala de 90 m e foram reprojetadas para o _DATUM_ _WGS84_.

### Diversidade da paisagem

O cálculo de diversidade da paisagem foi realizado no *Google Earth Engine* [@gorelick_google_2017] e é composto por médias feitas pixel a pixel entre os maiores valores padronizados ( _Z-scores_ ) das imagens: [__Variedade de _landforms___](#variedade-de-landforms), [__Amplitude altitudinal__](#amplitude-altitudinal), [__Valores de áreas úmidas__](#valores-de-áreas-úmidas) e [__Diversidade de solo__](#diversidade-de-solo). Utilizamos o *Google Earth Engine* devido a demanda computacional das análises e por ser uma plataforma baseada em nuvem, que oferece acesso remoto a uma vasta coleção de imagens de satélite e bases de dados geoespaciais de acesso livre e com capacidade computacional para realizar as análises em qualquer equipamento disponível [@gorelick_google_2017]. Isso possibilita que nossas análises sejam de livre acesso, escalonáveis para outras regiões do mundo e que contribuam para uma ciência mais transparente, reproduzível e livre.

#### Variedade de _landforms_

A classificação e distribuição espacial de _lanforms_ (formas de relevo) são a base para o cálculo da **diversidade da paisagem** e representam áreas com maiores estabilidade microclimática que resistirão aos impactos causados pelas mudanças climáticas [@anderson_resilient_2016]. Essa classificação é baseada em combinações de informações sobre a **inclinação** (_slope_), **orientação do relevo** (_aspect_), **indice de posição topográfica** (_topographic position index_), **índice de umidade** (_moisture index_) e a distribuição de **rios** e **lagos** <!-- e **áreas úmidas**--> dos ambientes. A combinação dessas variáveis representa a variação de umidade, radiação solar e deposição de sedimentos [@anderson_resilient_2016] na paisagem.

A metodologia de classificação de formas de relevo foi baseada em estudos prévios conduzidos pela equipe da [**TNC América do Norte**](https://crcs.tnc.org/pages/land), publicada inicialmente em 2014 [@anderson_estimating_2014] e refinada em estudos posteriores [@anderson_resilient_2023].
<!--Adaptamos a metodologia aplicada anteriormente, utilizando o TPI ao invés do LPI... [Lucas, sugiro algo nessa linha, indicando quais alterações fizemos na metodologia anterior -->

Para o cálculo de [inclinação](#inclinação-do-relevo), [orientação do relevo](#orientação-do-relevo) e [índice de posição topográfica (TPI)](#índice-de-posição-topográfica), utilizamos o modelo digital de elevação (DEM) do Merit-DEM [@yamazaki_high-accuracy_2017], em uma escala de 90 m. Escolhemos utilizar esse DEM por ser um produto em escala global, de livre acesso e com correções de vários viéses de modelos de elevação, principalmente viéses de elevação em áreas com alta densidade de florestas. Além disso, o Merit-DEM já possui um [acúmulo de fluxo](#acúmulo-de-fluxo) calculado sobre ele, em escala global, disponível no Merit-Hydro [@yamazaki_merit_2019]. Essa camada de acúmulo de fluxo é corrigida para o efeito da densidade de árvores no cálculo da rede hidrográfica da região [@yamazaki_merit_2019], o que possibilita que nosso trabalho seja replicável e mais próximo da realidade dos biomas que modelamos.

Para complementar a superfície gerada pelo acúmulo de fluxo e definir a presença de **rios** e **lagos** <!--e **áreas umidas** -->, nós incluímos as classes de água do MapBiomas Coleção 7 [@mapbiomas_project_collection_2020]. O MapBiomas é um projeto nacional de mapeamento e classificação de mudanças do uso do solo dos últimos 30 anos, a partir de dados de sensoriamento remoto.


##### Índice de posição topográfica (TPI)

O cálculo do TPI foi feito em três escalas com uma janela circular com 7, 11 e 15 células de raio, calculando a diferença da média de elevação entre a célula focal e um conjunto de células vizinhas ($i$), divididos pelo número de células vizinhas ($n$).

$$
TPI = \frac {\sum  _{i}^{n}\left(vizinhança_i - focal \right)}{n}
$$

O índice é composto pela média de TPI das três escalas, o que permite a consideração de níveis locais e regional de resolução da paisagem [@theobald_ecologically-relevant_2015]. Os tamanhos das janelas foram definidos visualmente para que melhor representassem as formas de relevo.

##### Orientação do relevo
A orientação do relevo é calculado como um gradiente local das 4 células adjacentes. Os resultados são apresentados em graus, que representam a direção do relevo (0º = Norte, 90º = Leste, 180º = Sul e 270º = Oeste). Nós dividimos a orientação do relevo em dois grupos, baseados na quantidade de incidência solar, sendo células com valores entre 90º e 270º classificados como **faces frias** e valores entre 0º a 90º e 270º a 360º, classificados como **faces quentes**.

##### Inclinação do relevo
A inclinação do relevo é calculada como um gradiente local das 4 células adjacentes, os resultados são apresentado em graus que representam a inclinação do relevo (0º a 90º). 

<!-- A inclinação foi dividida em 5 grupos baseado em faixas de inclinação, para melhor classificar diferentes formas do relevo (@tbl-inclinacao).

|Inclinação|Grupo|
|--:|--:|
|0º a 2º  | 1 |
|2º a 6º  | 2 |
|6º a 24º | 3 |
|24º a 35º| 4 |
|35º a 90º| 5 |
: Classes de declividade usadas para a classificação de _landforms_ {#tbl-inclinacao}
-->

##### Índice de umidade
O índice de umidade (_moisture index_) foi calculado com base no **acúmulo de fluxo** do Merit-Hydro e a **inclinação do relevo** que calculamos anteriormente.
$$
moisture.index = \frac{\log \left(fluxo+1\right)}{\left(slope+1\right)}  \times1000
$$
O índice de umidade é a média do índice dentro de uma janela circular de uma célula de raio determinado. O tamanho do raio foi escolhido visualmente para suavizar o índice, mas representando bem a distribuição dos cursos d'água.

<!--
Classificamos como áreas úmidas somente regiões que apresentassem um valor do índice de umidade acima de 3000 e definimos esse valor para que visualmente pudéssemos capturar a distribuição dos cursos d'água sem superestimar outras áreas planas. Porém, esse corte do índice não consegue classificar bem corpos de água com grandes extensões (por exemplo, rio Amazonas, represas e grandes lagos), por isso nós corrigimos a classificação sobrepondo a camada do índice de umidade com a camada de águas do MapBiomas.
-->
#### Transformando os índices em classes

Cada índice (TPI, inclinação, orientação e índice de úmidade) foi transformado em classes (@tbl-classes) para formarem os tipos de *landforms*. O índice umidade é classificado como presença ou ausência de umidade, sendo locais com rios e lagos classificados como presença.  

| Variáveis | Classes | Limiar inferior | Limiar superior |
|:-:|:-:|:-:|:-:|
| Inclinação do relevo|1|-1|2|
|Inclinação do relevo|2|2|6|
|Inclinação do relevo|3|6|24|
|Inclinação do relevo|4|24|35|
|Inclinação do relevo|5|35|90|
|TPI|1|-Inf|-15|
|TPI|2|-15|-1|
|TPI|3|-1|30|
|TPI|4|30|975|
|Aspecto|2|0|90|
|Aspecto|1|90|270|
|Aspecto|2|270|360|
|Índice de Umidade|0|-Inf|30000|
|Índice de Umidade|1|3000|Inf|
: Classes dos índices usados para a classificação de _landforms_ {#tbl-classes}

##### Combinando as variáveis e classificando as _landforms_

A partir das classificações de todas as variáveis, geramos um código representativo das combinações de classificações das localidades. A classe do índices de umidade é multiĺicado por 1000, orientação do relevo por 100, TPI por 10 e inclinação do relevo por 1. Dessa forma, podemos representar as classes dos índices de uma localidade por um único número. Por exemplo, o código 11 representa áreas de baixa inclinação do relevo e uma posição do relevo mais alta que o entorno, sendo portanto um topo de montanha (_summit_). No entanto, alguns códigos tiveram que ser inspecionados visualmente para classificar alguns tipos de _landforms_, como _sideslopes_, _valleys_ e _toeslopes_ (@tbl-combinacoes).

|Valores da Combinação| Código para Landforms|
|--:|--:|
|10| 11|
|11| 11|
|12| 11|
|13| 13|
|14| 11|
|15| 5|
|20| 21|
|21| 21|
|22| 22|
|23| 24|
|24| 24|
|25| 5|
|31| 30|
|32| 32|
|33| 24|
|34| 24|
|35| 5|
|40| 32|
|41| 32|
|42| 32|
|43| 43|
|44| 3|
|45| 5|
|51| 51|
|111| 11|
|112| 11|
|113| 13|
|114| 3|
|115| 5|
|121| 21|
|122| 22|
|123| 23|
|124| 3|
|125| 5|
|131| 30|
|132| 32|
|133| 23|
|134| 3|
|135| 5|
|141| 32|
|142| 32|
|143| 43|
|144| 3|
|145| 5|
|151| 51|
|211| 11|
|212| 11|
|213| 13|
|214| 4|
|215| 5|
|221| 21|
|222| 22|
|223| 24|
|224| 4|
|225| 5|
|231| 30|
|232| 32|
|233| 24|
|234| 4|
|235| 5|
|241| 32|
|242| 32|
|243| 44|
|244| 4|
|245| 5|
|251| 51|
|1000| 39|
:Combinações entre as variáveis para classificar as formas de relevo {#tbl-combinacoes}

A classificação final de landforms se encontra na @tbl-landforms.

|Códigos | Nomes|
|--:|--:|
|3 |Cool Steep Slope  |
|4 | Warms Steep Slope  |
|5 |Cliff  |
|11 | Summit/Ridgetop  |
|13 | Slope Crest  |
|21 | Flat Hilltop  |
|22 | Gentle Slope Hilltop|
|23 | Cool Sideslope  |
|24 | Warm Sideslope  |
|30 | Dry Flats  |
|32 | Valley/Toeslope|
|39 | Moist Flats  |
|43 | Cool Footslope  |
|44 |Warm Sideslope|
: Códigos das formas de relevo obtidas após classificação das variáveis {#tbl-landforms}

<!-- Seria interessante algumas figuras de exemplos de landforms dentro dos biomas!!-->

##### Gerando a variedade de _landforms_
A variedade de _landforms_ foi calculada como quantidade de tipos de _landforms_ dentro de um _kernel_ circular da célula focal. O tamanho do raio do kernel foi definido calculando a variedade em diferentes raios (2, 5, 7, 10, 15, 20 células) e calculando o ganho de variedade a cada aumento de raio. O raio escolhido foi aquele em que o seu subsequente não adicionou variedade. 

Desta forma, o raio representa o nível de resolução da paisagem que captura o máximo de variedade de landforms. <!-- Raios maiores podem aumentar a variedade, mas devido a mudança de paisagem. --> Assim, o raio escolhido foi de 5 células de raio (450 m) para todo o Brasil.
Por fim, calculamos os valores de Z para cada pixel ($Z_{pixel}$) ao subtrair o valor da média ($\mu$) e dividindo o resultado pelo desvio padrão ($\sigma$), como mostrado na fórmula a seguir:
$$
Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}
$$
Os cálculos de $Z$ foram feitos dentro de cada classificação de **regiões eco-geológicas** usando médias e desvios padrão dentro de cada uma das classes.

#### Amplitude altitudinal

A amplitude altitudinal representa a variação da elevação em uma região, independente do número de [___landforms___](#variedade-de-landforms), controlando a relação entre ambas já que elas são correlacionadas entre si. A amplitude altitudinal foi calculada como a diferença entre os valores máximos e mínimos de elevação, dentro de um _kernel_ circular de 450 m, a partir dos dados do DEM do MERIT [@yamazaki_high-accuracy_2017]. fizemos então uma Regressão Linear Simples (_Ordinary Linear Regression_) entre os **valores de amplitude altitudinal** e a **variedade _landforms_** e obtivemos os valores dos resíduos dessa análise para diminuir a correlação estre as duas variáveis.

Por fim, os valores da variação desses resíduos da correlação entre a amplitude e a variedade da forma de relevo, para cada pixel ($Z_{pixel}$), podem ser calculados ao subtrair o valor da média ($\mu$) e dividir o resultado pelo desvio padrão ($\sigma$), como mostrado na fórmula a seguir:
$$Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}$$

Dessa forma, temos uma imagem que mostra a variação, em relação à média, dos valores dos resíduos da amplitude altitudinal dentro de cada uma das categorias de regiões eco-geológicas.

#### Índice de áreas úmidas

Para calcular o índice de áreas úmidas, utilizamos os dados disponibilizados na base de dados _Global Wetlands Database_ [@gumbricht_tropical_2017], que é uma base de dados que fornece informação e inventário de áreas úmidas no mundo. Os dados são obtidos através de imagens de satélite, amostragens aéreas e relatórios publicados. Como áreas úmidas ocorrem em diversas configurações e distribuições no espaço, nós avaliamos a densidade e o número de áreas úmidas em escala local (450 metros) e escala regional (1170 metros).
A **densidade de áreas úmidas** foi calculada como a média do número de _pixels_  de áreas úmidas, dentro de um _kernel_ de escala regional (1170 m) e um kernel em escala local (450 m).
Já a **contagem em escala local** foi calculada como uma contagem de _pixels_ dentro de um _kernel_ circular em escala regional (1170 metros). A contagem vai representar o número de áreas umidas ao redor do _pixel_ focal, mostrando regiões de maiores quantidades de áreas úmidas, mas em baixa densidade.

Essas 3 camadas vão auxiliar na identificação de regiões de diversidade da paisagem que apresentem valores baixos para formas de relevo e amplitude de elevação, mas que tenham um acúmulo de áreas umidas que poderiam amenizar localmente o efeito das mudanças climáticas [@anderson_resilient_2016].

Para calcular os **valores finais do índice de áreas úmidas**, é necessário juntar as informações das camadas de **densidade local**, **densidade regional** e a **contagem em escala local**. Começamos calculando valores padronizados para cada uma delas ($Z_{local}$, $Z_{regional}$ e $Z_{contagem}$, respectivamente) ao subtrair os valores de pixels ($X_{pixel}$) pela média ($\mu$) e dividirmos o resultado pelo desvio padrão ($\sigma$) dentro das diferentes categorias de [__regiões eco-geológicas__](#regiões-eco-geológicas), como na fórmula:
$$
Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}
$$

Com o $Z$ calculado para as 3 camadas, podemos calcular o índice de áreas úmidas ($Z_{úmidas}$) ao fazermos uma média dos valores para as camadas de densidade local, densidade regional e contagem.

Primeiro calculamos a média ($Z_{densidade}$ entre as imagens de valores de densidade de áreas úmidas em escala local ($Z_{local}$) e regional ($Z_{regional}$), atribuindo mais peso para os valores da densidade local:
$$
Z_{densidade}=\frac {{{(Z_{local}}{\times2)}}+{Z_{regional}}}{3}
$$
Ao compararmos esse resultado com a camada de contagem regional, podemos identificar os locais onde os valores para densidade ($Z_{densidade}$) são menores que os valores de contagem ($Z_{contagem}$) e calculamos a média para esses pixels, novamente dando mais peso ao valores de densidade:

$$
Z_{úmidas}=\frac {{{(Z_{densidade}}{\times3)}}+{Z_{contagem}}}{4}
$$
Ao final de todas as operações, temos uma única camada com valores que representam a variação em relação à média dos valores de densidade e contagem de pixels de áreas úmidas referentes às regiões eco-geológicas.

#### Diversidade de solo

A diversidade de solo foi calculada como a distribuição do número de classes de solo, dentro de um _kernel_ de 1350 m. Ela foi usada para indicar áreas com grande concentração dos diferentes tipos de solo que vão afetar diretamente na diversidade de espécies no ambiente. Para calcular o raster de diversidade do solo usamos a classificação oficial dos solos brasileiros, disponibilizada pelo [Instituto Brasileiro de Geografica e Estatística (IBGE)](https://www.ibge.gov.br/geociencias/informacoes-ambientais/pedologia/10871-pedologia.html).

Como a classificação do IBGE foi disponibilizada em formato de _shapefile_, começamos a análise separando cada uma das 108 classes de solo do Brasil e calculamos um raster de presença e ausência do tipo de solo. Ao final do processo podemos somar os diferentes mapas de presença para obter os mapas de diversidade do solo, onde os maiores valores de cada pixel mostram áreas com concentração de diferentes tipos de solo.

Por fim, calculamos os valores de Z para cada pixel ($Z_{pixel}$) ao subtrair o valor da média ($\mu$) e dividindo o resultado pelo desvio padrão ($\sigma$), como mostrado na fórmula a seguir:
$$Z_{pixel}= \frac {X_{pixel}-\mu} {\sigma}$$
Os cálculos de $Z$ foram feitos dentro de cada classificação de regiões eco-geológicas usando as médias e desvios padrão dentro de cada uma das classes.

#### Cálculo da Diversidade da Paisagem


### Conectividade local

#### Cálculos de resistência

Os valores de resistência são medidas relativas do grau de dificuldade de deslocamento dos organismos nos diferentes tipos de cobertura do solo. Esses valores foram atribuídos por bioma, seguindo a premissa de que quanto maior for a diferença estrutural entre um dado tipo de cobertura do solo e a vegetação original do bioma, maior será o valor de resistência da classe de cobertura do solo em questão.

Os dados espaciais primários utilizados para calcular a superfície de resistência foram a camada de cobertura do solo fornecida pelo MapBiomas [@mapbiomas_project_collection_2020] e a base de estradas pavimentadas e não pavimentadas fornecida pelo IBGE (BCIM250, ano 2021). Em um segundo momento, serão ainda inseridas bases de dados de infraestrutura energética, a serem incorporadas nessa camada.

A superfície de cobertura do solo do MapBiomas foi reamostrada para gerar pixels com 90 m de tamanho, aproximadamente. Também convertemos o arquivo vetorial de estradas para o formato matricial, com pixels de tamanho aproximado de 90 m. Conjugamos, por álgebra de mapas, as bases matriciais do MapBiomas e de estradas, de tal maneira que todos os pixels da base do MapBiomas que se sobrepuseram a um pixel de estrada assumiram um novo valor correpondente a um pixel de estrada pavimentada ou não pavimentada.

Os pixels do mapa consolidado de cobertura do solo, já incluindo as estradas pavimentadas e não pavimentadas como novas classes, receberam, separadamente por bioma, valores de resistência que buscaram traduzir, comparativamente entre as classes, o grau de dificuldade de movimentação da biodiversidade numa dada classe de cobertura do solo. A premissa assumida aqui é que quanto maior for a diferença estrutural da classe de cobertura do solo para o hábitat original do bioma, maior será a dificuldade à movimentação que esta classe oferece. Os valores de resistência dos pixels de cada uma das classes foram atribuídos, por bioma, pela equipe do Projeto e podem ser vistos na @tbl-resistencia.

|Classe de cobertura do solo|Amazônia|	Caatinga|	Cerrado	|MataAtlântica|	Pampa	Pantanal|
|--:|--:|--:||--:|--:|--:|--:|
|Aquaculture|-	|10	|7	|7	|7	|- |
|Beach, Dune and Sand Spot|2	|2	|2	|2	|2	|- |
|Citrus|-	|-	|10	|10	|-	|- |
|Coffee|-	|7	|10	|10	|-	|- |
|Cotton|7	|7	|10	|-	|-	|- |
|Estradas não pavimentadas|10	|10	|7	|10	|7	|7 |
|Estradas pavimentadas|20	|20	|20	|20	|20	|20|
|Forest Formation|1	|1	|1	|1	|1	|1 |
|Forest Plantation|7	|2	|7	|3	|10	|5 |
|Grassland|2	|1	|1	|2	|1	|1 |
|Herbaceous Sandbank Vegetation	|-	|1	|-	|2	|1	|- |
|Mangrove|1	|1	|1	|1	|-	|- |
|Mining|20	|20	|20	|20	|20	|20|
|Mosaic of Uses|7	|7	|10	|10	|10	|10|
|Other non Forest Formations|-	|-	|-	|7	|-	|- |
|Other non Vegetated Areas|-	|9	|10	|10	|10	|10|
|Other Perennial Crops|7	|7	|10	|10	|-	|- |
|Other Temporary Crops|15	|7	|10	|10	|10	|10|
|Pasture|15	|7	|5	|9	|5	|7 |
|Rice|-	|-	|10	|10	|10	|- |
|River, Lake and Ocean|2	|5	|5	|5	|5	|2 |
|Rocky Outcrop|-	|1	|2	|2	|2	|- |
|Salt Flat|2	|1	|2	|2	|-	|- |
|Savanna Formation|2	|1	|1	|2	|-	|2 |
|Soybean|15	|10	|10	|10	|10	|10|
|Sugar cane|15	|10	|10	|10	|-	|10|
|Urban Area|20	|20	|20	|20	|20	|20|
|Wetland| 1	|-	|1	|1	|1	|1 |
|Wooded Sandbank Vegetation|-	|1	|-	|1	|1	|- |
: Valores de resistência para cada tipo de cobertura por bioma {#tbl-resistencia}


Depois de atribuídos os valores de resistência, aplicamos à superfície gerada a função _kernel_ de decaimento linear. Esta análise considerou, numa janela móvel de 23 pixels (~2070 m), o contexto espacial em que cada pixel está inserido, reconhecendo que pixels mais próximos possuem uma influência maior que os mais distantes. Desta maneira, a função _kernel_ nos auxilia na tarefa de encontrar os melhores caminhos de deslocamento na paisagem, ou seja, aqueles caminhos que oferecem menor resistência.

Por fim, calculamos os valores de Z para cada pixel ($Z_{pixel}$) ao subtrair o valor da média ($\mu$) e dividindo o resultado pelo desvio padrão ($\sigma$) e multiplicando tudo por -1, como mostrado na fórmula a seguir:
$$
Z_{pixel}= \left(\frac {X_{pixel}-\mu} {\sigma}\right) \times -1
$$
Os cálculos de $Z$ foram feitos dentro de cada classificação de regiões eco-geológicas usando as médias e desvios padrão dentro de cada uma das classes. Multiplicamos o valores por -1 por considerarmos que a conectividade local é o inverso dos valores de resistência suavizados pelo _kernel_.


<!-- Os dados espaciais primários para calcular a superfície de resistência foram a camada de cobertura do solo fornecida pelo MapBiomas [@mapbiomas_project_collection_2020] e a base de estradas fornecida pelo IBGE (BCIM250 de 2021). Os seguintes passos foram realizados:
1.	Os pixels da camada do MapBiomas foram reamostrados de 30 metros par 90 metros, usando a ferramenta “Ressample” do software ArcGis 10.5
2.	O shapefile de estradas do IBGE foi convertido para o formato raster, com pixels de aproximadamente 90 metros de tamanho. Os pixels correspondentes a estradas pavimentadas receberam o valor de 2000, os pixels de estradas não pavimentadas receberam o valor de 1000 e os demais pixels (que não correspondem a nenhuma estrada) receberam o valor de 0 (zero)
3.	No ArcGis 10.5, usando a ferramenta “Map Calculator” as camadas de cobertura do solo e de estradas foram somadas. Na superfície gerada, foram mantidos os valores dos pixels, originalmente atribuídos pelo MapBiomas, quando um pixel de cobertura do solo se sobrepusesse a algum pixel da camada de estradas com valor igual a zero. Nos casos onde os pixels de cobertura do solo se sobrepuseram a um pixel de estrada pavimentadas o valor final desses pixels foi reclassificado para 98 e quando a sobreposição ocorreu com algum pixel de estrada não pavimentada, o valor final foi reclassificado para 99
4.	Na superfície gerada, os pixels de cada uma das classes receberam valores de resistência, inferidos separadamente para cada bioma (obs: neste arquivo os valores de resistência foram inferidos pela equipe de bolsistas de pós-doutorado do Projeto e seus supervisores, com auxílio da equipe da TNC). Os valores de resistência para cada classe de uso e cobertura do solo, por bioma, encontram-se na tabela 1 (abaixo). Os valores de resistência buscaram traduzir, comparativamente entre as classes, o grau de dificuldade de movimentação de um dado animal ou propágulo naquela classe de cobertura do solo. A premissa assumida aqui, para todos os biomas, é que quanto maior fora a diferença estrutural daquela classe para o hábitat original do bioma, maior será a dificuldade de movimentação por um dado pixel
5.	Depois de atribuídos os valores de resistência, usando a ferramenta “Focal Statistics” do ArcGis 10.5, foi calculada o valor médio do pixel focal, em um raio de 23 pixels, aplicando a função de _Kernel_, com decaimento linear. Esta análise considera o contexto espacial em que cada pixel está inserido, reconhecendo que pixels mais próximos possuem uma influência maior um sobre o outro do que pixels mais distantes -->


### Resiliência: combinando diversidade da paisagem e conectividade local
 A **resiliência da paisagem** é definida como a capacidade de um local manter a diversidade de espécies e funções ecossistêmicas perante as pressões impostas por mudanças climáticas. Ela foi calculada como a média entre os valores padronizados (${Z}$) de [__diversidade da paisagem__](#diversidade-da-paisagem) e [__conectividade local__](#conectividade-local).
 
<!-- Para melhorar a visualização e comparação entre os valores de diversidade da paisagem e conectividade local calculamos os quartis de 5% e 95% e limitamos os valores maiores que 95% e menores que 5%. Fazemos isso so para landscape e é para filtrar outliers, não melhorar a visualização
 -->


<!--
## Conectividade regional

Calculamos a conectividade regional baseada em teoria de circuitos [@mcrae_isolation_2006] utilizando a implementação de Omniscape para Julia [@hall_circuitscape_2021; @landau_omniscapejl_2021].

Como base para estas análises, utilizamos:

+ o raster de resistência calculado acima com o filtro de _kernel_ utilizado como base para a conectividade local e subamostrado para uma resolução de 900m por pixel,
+ um raio da área de interesse de 100 píxeis (~90km)
+ agrupamentos de 5 píxeis de interesse para a janela móvel (~4.5km).

O output de Omniscape são três arquivos de conectividade relacionados:

+ `flow_current` é o fluxo que aconteceria sem levar em conta a camada de resistência. Ele leva em conta a configuração espacial da paisagem (estreitos, barras) e dos píxeis de baixa resistência de origem. Nem todo pixel é source pixel, mas a corrente que entra em cada pixel de baixa resistência entra sem resistência. Flow current é usado como um "modelo nulo" de conectividade.
+ `cumulative_current` é a corrente levando em conta a configuração espacial e os valores de resistência
+ `normalized_current` equivale a $\frac{cumulative\_current}{flow\_current}$
e controla o efeito da configuração espacial do cálculo de conectividade.

Os resultados da análise nesta escala espacial foram reclassificados de acordo com a distribuição ao redor da média dos valores nas categorias seguintes:

+ Entre o valor mínimo e média - 0,5 desvio padrão: fluxo impedido. O fluxo não consegue circular devido à presença de áreas de alta resistência, podendo se redirecionar em torno a essas áreas
+ Entre média - 0,5 desvio padrão e média + 1 desvio padrão: fluxo difuso. O fluxo consegue se dispersar em áreas contíguas de resistências baixas a moderadas, sem se ver impedido ou canalizado
+ Entre média + 1 desvio padrão e média + 2 desvios padrão: fluxo intensificado. O fluxo potencial se concentra devido à configuração da paisagem ou de áreas de alta resistência que forçam um rumo determinado
+ Maior que a média + 2 desvios padrão: fluxo canalizado. Fluxo muito acima do esperado em uma área sem resistência. Ele passa por estreitos, barras de areia e estruturas similares.

-->
