
# Síntese do projeto {.unnumbered}

## Contexto geral do estudo

As mudanças no clima modificam ambientes naturais e pressionam espécies a se adaptarem às novas condições ambientais ou alterarem suas distribuições espaciais para locais mais adequados climaticamente.
A identificação de locais com adequabilidade climática para sustentar a biodiversidade no futuro de mudanças climáticas é imprescindível para o planejamento sistemático de ações de conservação e restauração.


## O que queremos fazer?
O objetivo principal do projeto é __mapear sítios resilientes às mudanças climáticas__, que permitam a movimentação da biodiversidade na busca de áreas mais adequadas climaticamente.

O termo _áreas resilientes_ indica locais que apresentam condições necessárias para que espécies e processos ecológicos persistam às mudanças climáticas regionais, definidos por sua alta diversidade microclimática e conectividade. 


## Quais as premissas básicas desse estudo?
A metodologia desenvolvida segue três premissas básicas:

1. A diversidade da paisagem é determinada pela heterogeneidade de habitats, variáveis condicionadas por características do meio físico, como feições topográficas, altitude, disponibilidade hídrica e tipo de solo, e que promovem variabilidade microclimática, influenciando diversidade genética e fenotípica de espécies.

2. A conectividade da paisagem é determinada pela resistência que os tipos de uso e cobertura do solo oferecem para a movimentação das espécies na paisagem, considerando as relações de vizinhança estabelecidas em uma escala local.

3. A resiliência da paisagem a mudanças do clima é determinada pela heterogeneidade de habitat disponíveis para as espécies, que geram condições diversificadas de microclimas aos organismos, e pela conectividade desses habitats na paisagem, que permitem a movimentação desses organismos para áreas mais adequadas.


## Qual metodologia estamos utilizando?
A metodologia proposta para isso combina a diversidade da paisagem, um _proxy_ da variabilidade microclimática, com a conectividade local, identificando locais que forneçam condições microclimáticas para o enfrentamento às mudanças climáticas, cujas matrizes da paisagem sejam permeáveis à movimentação das espécies.

A diversidade da paisagem é baseada na geodiversidade (geomorfologia, geologia, pedologia e hidrologia) do terreno, composta pela variedade de formas de relevo, amplitude altitudinal, densidade de áreas úmidas e riqueza de solos.

A conectividade local é baseada na resistência das matrizes da paisagem ao movimento da biodiversidade, combinando uso do solo e infraestruturas de transporte e de energia existentes (com maior ou menor grau de antropização).


## Por que a escolha por essa metodologia de análise?
Essa análise foi proposta e validada para a América do Norte pela _The Nature Conservancy_ (TNC), complementando outras metodologias disponíveis na literatura, uma vez que ela foca nas propriedades do terreno para identificar áreas resilientes. 

A aplicação da metodologia da TNC para os biomas brasileiros é um passo importante na identificação de sítios resilientes em ambientes tropicais megadiversos. 
Atuando em conjunto com especialistas dos diferentes biomas e baseado na literatura disponível, o projeto busca adequar a metodologia original ao contexto dos biomas brasileiros, refinando e adaptando quando necessário.


## Onde e com quem estamos trabalhando?
O mapeamento está sendo conduzido para cada um dos seis biomas do Brasil.
Para isso, em cada um dos biomas temos coordenadores(as) responsáveis em instituições de pesquisa, além de um(a) pesquisador(a) de pós-doutorado diretamente envolvido(a) no projeto. Há ainda uma equipe de especialistas, de diversas áreas de atuação relacionadas à 
Temática do projeto, que participam como colaboradores do desenvolvimento do estudo.


## Quais são os produtos previstos desse projeto?
O produto resultante desse projeto é um mapa de áreas resilientes e conectadas para os biomas do Brasil que permite identificar áreas com potencial de sustentar animais e plantas em um clima sob mudanças.
Está em construção também um relatório técnico descrevendo o projeto e a metodologia utilizada, além de uma documentação reproduzível das análises.
Além desses produtos, está prevista a elaboração de, no mínimo, um artigo científico a ser submetido a uma revista científica internacional.


## Como temos conduzido as atividades?
Os(as) bolsistas de pós-doutorado têm sido responsáveis por liderar as análises e conduzir o projeto regionalmente. A equipe da TNC Brasil coordena as atividades em cada bioma e entre os biomas e também a integração entre as diversas equipes, participando diretamente das discussões nos grupos.
Estão sendo realizadas oficinas e reuniões virtuais com as equipes de cada bioma e com os(as) especialistas para discutir as particularidades regionais, refinar as análises e os resultados obtidos.


## Palavras chave
Resiliência climática, mudanças climáticas, conectividade, paisagem, geodiversidade, conservação, biodiversidade.


## Instituições parceiras do projeto



[INSERIR LOGO DAS INSTITUIÇÕES: TNC, MPEG, UFABC, UFJ, UFMS, UFRN; SOS Pantanal, Associação Caatinga]

