# Introdução

As mudanças climáticas têm alterado os regimes de temperatura e pluviosidade global, impactando a fenologia, o comportamento e a distribuição geográfica das espécies (Vitasse et al. 2018; Hannah, 2021; McCain et al 2014; IPCC 2022; Antão et al. 2022). As espécies têm sofrido mudanças nos limites das suas distribuições para localidades mais temperadas e de maior altitude (Nabout et al. 2011; Lemes, Priscila et al. 2014,  Gillings et al 2015; Abreu-Jardim, Tatianne P.F. et al. 2021). Essas mudanças nas distribuições geográficas modificam a composição de espécies das comunidades ecológicas, causando disrupção de interações inter-específicas (Memmott et al 2007) e alterando a distribuição de atributos funcionais (Bender et al 2019), comprometendo o provimento, regulação e suporte de funções, estrutura e dinâmica ecossistêmica (montoya_raffaelli_2010?).

O impacto das mudanças climáticas não é uniforme na superfície do globo, uma vez que a vulnerabilidade das espécies depende da sua exposição e sensibilidades às mudanças ambientais [Williams, Stephen E. et al. (2008); Folden et al. 2018]. A exposição é caracterizada pela forma como as mudanças globais, regionais e locais atuam diretamente nos organismos pela interação entre variáveis climáticas, bióticas, pedológicas, hidrológicas e topográficas, que configuram  as condições microclimáticas e dos habitats onde as espécies vivem. Por outro lado, a sensibilidade depende da plasticidade fisiológica, morfológica e comportamental das espécies, seu potencial de adaptação às novas condições ambientais e capacidade de dispersar para áreas adequadas ambientalmente. Dessa forma, dependendo do grau de exposição, as espécies podem continuar nas suas localidades ou buscar áreas adequadas, dependendo da velocidade com que o clima muda local e regionalmente (Loarie, Scott R. et al. 2009). Locais com alta velocidade climática possuem alta taxa de mudança local ou baixa diferença climática em relação ao entorno. Nesse cenário, as espécies precisam se locomover por maiores distâncias para encontrar áreas adequadas. Locais com baixa velocidade climática possuem baixa mudança climática ao longo do tempo ou alta variabilidade climática no entorno, possibilitando a manutenção na localidade ou a busca por regiões adequadas em localidades próximas (Souza et al. 2023). Assim, as espécies necessitam de uma rede de localidades não somente climaticamente adequadas, como também com baixa resistência à movimentação dado o uso e cobertura do solo (Mantyka-Pringle et al. 2011; Borges & Loyola 2020).

As paisagens naturais têm sido severamente degradadas pela mudança no uso e cobertura do solo em decorrência da atividade antrópica (fao_coppus_2023?; Newbold et al. 2015; Winkler et al. 2021; Cordier et al. 2021, Semenchuk et al 2022). A perda e fragmentação de habitat causada pelo desmatamento e conversão da vegetação nativa estão entre as principais causas de ameaça de extinção das espécies (Harfoot et al 2021; Dias et al. 2019; Pardini_et_al_2017?), tanto por reduzir a capacidade de suporte populacional quanto por diminuir a permeabilidade, alterar as dinâmicas metapopulacionais e a riqueza das comunidades (Haddad et al 2015; Hanski & Ovaskainen 2000; chase_2020?). Além disso, a perda e fragmentação de habitat reduzem a capacidade das espécies de se movimentarem na paisagem na busca por condições climáticas adequadas, aumentando a velocidade da mudança climática nas paisagens mais degradadas. Portanto, estratégias adequadas de conservação dependem de abordagens integrativas que considerem esses efeitos múltiplos e sinérgicos das mudanças globais sobre a distribuição das espécies (Sirami et al 2016; Días et al 2019).

Os estudos sobre os impactos das mudanças climáticas na distribuição da biodiversidade têm como base modelos que combinam informações sobre a distribuição das espécies e dados de projeções climáticas para diferentes períodos de tempo (Costello et al. 2022). Essas projeções climáticas utilizam modelos globais e regionais, possibilitando a identificação de áreas mais vulneráveis, refúgios climáticos e a projeção dos impactos futuros (Terribile et al. 2012; Lima et al. 2017). No entanto, os modelos climáticos fornecem dados em escalas regionais ou como interpolações em baixa resolução (Lima-Ribeiro, Matheus S et al. 2015, Fick e Hijmans 2017, Karger, Dirk Nikolaus et al. 2017), limitando o diagnóstico e desenvolvimento de estratégias de mitigação em escalas mais locais, onde as ações devem ser desenvolvidas efetivamente. Uma abordagem complementar aos modelos climáticos, é a utilização da topografia, geodiversidade e aspectos fisiográficos (Anderson, Mark G. et al. 2014, Lawler, Joshua J. et al. 2015, Theobald et al. 2015) para diagnosticar, mapear e desenvolver soluções para a conservação em face às mudanças climáticas.

Nesse sentido, a geodiversidade da paisagem, caracterizada pelo conjunto de variáveis abióticas da superfície e subsolo terrestre (ex. topografia, geologia, pedologia e hidrologia) (Gray 2004), tende a ter baixa taxa de mudança no intervalo de tempo factível para ações de mitigação das mudanças climáticas (Lawler et al. 2015; Dobrowski 2011; mas veja Gill et al. 2015). Essas variáveis são componentes dos fatores determinantes de microclimas locais, como a superfície que mais recebe radiação solar, as posições no relevo mais expostas a ação de ventos, o direcionamento de ventos frios, o acúmulo de umidade e a retenção de água no solo (Dobrowski 2011). A interação entre a atmosfera e a topografia resulta em topoclimas, que tendem a ser relativamente desconectados do clima regional. Os locais onde o topoclima permite a manutenção das características microclimáticas, independente das mudanças regionais, têm sido definidos como locais potenciais para refúgios microclimáticos (Dobrowski 2011, Ashcroft et al. 2012). Além disso, locais com maior complexidade topográfica e amplitude altitudinal proporcionam maior variabilidade de condições ambientais para as espécies (Lawler et al 2015; Tukiainen et al 2022; Rahbek et al 2019). Desse modo, o potencial para atuar como refúgio microclimático e a maior variabilidade microclimática no entorno reduz a velocidade de mudança climática localmente.

O entendimento dos impactos das mudanças climáticas localmente necessita da compreensão dos seus impactos nas dimensões de biodiversidade, clima e geodiversidade, uma vez que todas essas variáveis se retroalimentam. Locais com maior geodiversidade são potencialmente mais resilientes às mudanças climáticas regionais tanto por amenizarem as mudanças microclimáticas locais, devido ao descolamento do topoclima com o clima regional, quanto pela disponibilidade de maior variabilidade microclimática (Lawler et al 2015; Dobrowski 2011; Tukiainen et al 2022). Além disso, locais com maior geodiversidade têm sido indicados com potencial de suportarem maior biodiversidade, em diferentes escalas espaciais (Fine 2015; Antonelli et al 2018; Tukiainen et al. 2018, Rahbek et al 2019; Vernham et al. 2023). Portanto, a geodiversidade tem surgido como uma alternativa para o desenvolvimento de estratégias de mitigação das mudanças climáticas, sobretudo pelos avanços teóricos e operacionais (Anderson et al 2014; Anderson et al 2023; Tukiainen et al 2022; Lawler et al 2015; Dobrowski 2011), como a maior disponibilidade de informações acessíveis em escalas espaciais finas (Zarnetske et al 2019, Cavender-Bares et al. 2020). Essa abordagem tem sido classificada como “conservar o palco da natureza” (do inglês conserving nature’s stage) (Anderson & Ferree 2010; Anderson et al 2014, 2023; Lawler et al 2015). Esse “palco” seria onde os “atores” da biodiversidade e as interações operam. A proposta é que a composição das comunidades provavelmente mudará ao longo do tempo, mas a manutenção das características abióticas que promovem e mantêm a biodiversidade permitiria a promoção da diversidade biológica, mesmo que os componentes originais se modifiquem.

Dentro desta abordagem, o primeiro mapeamento de áreas potencialmente resilientes às mudanças climáticas dada a sua geodiversidade foi realizado para ambientes temperados na América do Norte (Anderson et al. 2014, 2023). Nessa proposta, áreas resilientes são definidas como aquelas com alta diversidade de condições abióticas superficiais e do subsolo, que possuem baixa degradação ambiental e são conectadas na paisagem (Anderson et al 2014; 2023). Portanto, áreas resilientes teriam alta heterogeneidade de variáveis abióticas na paisagem e alta conectividade entre as manchas de habitat. Até o momento, ainda não estão disponíveis mapeamentos semelhantes de áreas resilientes para regiões tropicais e biodiversas, como é o caso do Brasil.


<!-- VERSÃO ANTERIOR - @LUCAS mantive por causa das referências, mas acredito que possa ser excluído

As mudanças climáticas estão alterando os regimes de temperatura e pluviosidade global, impactando a fenologia, o comportamento e a distribuição geográfica das espécies [@ipcc_climate_2022]. As espécies têm sofrido mudanças nas bordas das suas  distribuições para localidades mais temperadas e de maior altitude [@lemes_priscila_climate_2014; @abreu-jardim_tatianne_pf_predicting_2021]. Essas mudanças nas distribuições geográficas modificam a composição de espécies das comunidades ecológicas, causando disrupção de interações inter-específicas e distribuição de atributos funcionais, comprometendo o provimento, regulação e suporte de funções, estrutura e dinâmica ecossistêmica (@montoya_raffaelli_2010).

O impacto das mudanças climáticas não é uniforme ao longo do globo. <!-- o impacto é maior nos trópicos (Miguel Araujo heat freezes) --> A vulnerabilidade das espécies depende das suas exposições e sensibilidades às mudanças ambientais [@williams_stephen_e_towards_2008; Folden]. A exposição é caracterizada pela forma como as mudanças globais, regionais e locais atuam diretamente nos organismos pela interação entre variáveis climáticas, bióticas, pedológicas, hidrológicas e topográficas, na determinação das condições microclimáticas e dos habitats onde as espécies vivem. <!-- essa frase não está fazendo sentido, mas não entendi para conseguir editar --> Por outro lado, a sensibilidade depende da plasticidade fisiológica, morfológica e comportamental das espécies, sua adaptação às novas condições ambientais e capacidade de dispersar para áreas adequadas ambientalmente. Dessa forma, dependendo do grau de exposição, as espécies podem continuar nas suas localidades ou buscar áreas adequadas, dada a velocidade com que o clima muda localmente e regionalmente  [@loarie_scott_r_velocity_2009]. Locais com alta velocidade climática possuem alta taxa de mudança local ou baixa diferença climática em relação ao entorno. Nesse cenário, as espécies precisam se locomover por maiores distâncias para encontrarem áreas adequadas. Locais com baixa velocidade climática possuem baixa mudança climática ao longo do tempo ou alta variabilidade climática no entorno, possibilitando a manutenção na localidade ou a busca por regiões adequadas em localidades próximas. Assim, as espécies necessitam de uma rede de localidades não somente climaticamente adequadas, como também com baixa resistência à movimentação dado o uso e cobertura do solo. 

As paisagens naturais têm sido severamente degradadas pela mudança no uso e cobertura do solo causada pela atividade antrópica (@fao_coppus_2023; citações).
A perda e fragmentação de habitat é uma das principais causas de ameaça de extinção das espécies [@pardini_et_al_2017], tanto por reduzir a capacidade de suporte populacional quanto por diminuir a permeabilidade e alterar as dinâmicas metapopulacionais, o fluxo gênico e a riqueza das comunidades [@lienert_2004; @lowe_2005; @rivera-rivera_ortiz_2014; @barlett_et_al_2016, @chase_2020]. Além disso, a perda e fragmentação de habitat também reduz a capacidade das espécies de se movimentarem na paisagem na busca por condições climáticas adequadas, aumentando a velocidade climática nas paisagens mais degradadas. Portanto, estratégias adequadas de conservação dependem de abordagens integrativas que considerem esses efeitos múltiplos, e sinérgicos, das mudanças globais sobre a distribuição das espécies (Sirami et al 2016).

Os estudos sobre os impactos das mudanças climáticas na distribuição da biodiversidade tem como base modelos que combinam informações sobre a distribuição das espécies e dados de projeções climáticas para diferentes períodos de tempo. Essas projeções climáticas utilizam modelos globais e regionais, possibilitando a identificação de áreas mais vulneráveis, refúgios climáticos e a projeção dos impactos futuros (citação). No entanto, os modelos climáticos fornecem dados em escalas regionais ou como interpolações em resoluções mais finas [@fick_worldclim_2017; @karger_dirk_nikolaus_climatologies_2017; @lima-ribeiro_matheus_s_ecoclimate_2015], limitando o diagnóstico e desenvolvimento de estratégias de mitigação em escalas mais locais, onde as ações devem ser desenvolvidas efetivamente. Mesmo modelos microclimáticos, desenvolvidos para modelar mudanças em variáveis locais, são fornecidos globalmente em escalas regionais [@kearney_michael_r_microclim_2014]. Uma alternativa aos modelos globais e regionais é a utilização de séries temporais de dados climáticos derivados de sensoriamento remoto orbital [@hulley_g_viirsnpp_2018] ou estações metereológicas [@xavier_new_2022]. Nesse caso, apesar dos dados de longa duração possuírem escalas mais regionais (> 1km²), eles fornecem variabilidade de informação nessa escala, o que não é fornecido pelas interpolações dos modelos climáticos. Por outro lado, esses dados não possuem projeções para o clima futuro. Uma terceira abordagem, complementar aos modelos climáticos, é a utilização da topografia, geodiversidade e aspectos fisiográficos [@lawler_joshua_j_theory_2015; @anderson_mark_g_estimating_2014; @theobald_ecologically-relevant_2015] para diagnosticar, mapear e desenvolver soluções para as mudanças climáticas.

A geodiversidade da paisagem, caracterizada pelo conjunto de variáveis abióticas da superfície e subsolo terrestre (ex. topografia, geologia, pedologia e hidrologia), tende a ter baixa taxa de mudança no intervalo de tempo factível para ações de mitigação das mudanças climáticas. Essas variáveis são componentes dos fatores determinantes de microclimas locais, como por exemplo a superfície que mais recebe radiação solar, as posições no relevo mais expostas a ação de ventos, o direcionamento de ventos frios, o acúmulo de umidade e retenção de água no solo. A interação entre a atmosfera e a topografia resulta em topoclimas, que tendem a ser desconectados do clima regional. Os locais onde o topoclima permite a manutenção das características microclimáticas, independente das mudanças regionalmente, têm sido definidos como locais potenciais para refúgios microclimáticos. Além disso, locais com maior complexidade topográfica e amplitude altitudinal proporcionam maior variabilidade de condições ambientais para as espécies. O potencial para atuar como refúgio microclimático e a maior variabilidade microclimática no entorno reduz a velocidade climática localmente.

O entendimento dos impactos das mudanças climáticas localmente necessita da compreensão dos seus impactos nas dimensões de biodiversidade, clima e geodiversidade, uma vez que todas essas variáveis se retroalimentam. Locais com maior geodiversidade são potencialmente mais resilientes às mudanças climáticas regionais tanto por amenizarem as mudanças microclimáticas locais, devido ao descolamento do topoclima com o clima regional, quanto pela disponibilidade de maior variabilidade microclimática. Além disso, locais com maior geodiversidade têm sido demonstrados com potencial de suportarem maior biodiversidade, em diferentes escalas espaciais (Tukiainen et al. 2018, Vernham et al. 2023). Portanto, a geodiversidade tem surgido como uma alternativa para o desenvolvimento de estratégias de mitigação das mudanças climáticas, sobretudo pelos avanços teóricos <!-- (conservation biology, essential variables, tree) --> e operacionais, como a maior disponibilidade de informações acessíveis em escalas espaciais finas. Essa abordagem tem sido classificada como conservar o palco da natureza (do inglês **Conserving nature’s stage**), que é onde os atores da biodiversidade e as interações operam. A proposta é que a composição das comunidades muda ao longo do tempo, mas a manutenção das características abióticas que promovem e mantém a biodiversidade permite a promoção da diversidade biológica, mesmo que os componentes originais se modifiquem.

O primeiro mapeamento de áreas com potencialmente resilientes às mudanças climáticas dada a sua geodiversidade foi para a América do Norte (citação). Nessa proposta, áreas resilientes são definidas como aquelas com alta diversidade de condições abióticas superficiais e do subsolo, que possuem baixa degradação ambiental e são conectadas na paisagem (citação). Portanto, áreas resilientes teriam alta heterogeneidade de variáveis abióticas na paisagem e alta conectividade entre as manchas de habitat. A partir desse mapeamento, propusemos uma adaptação à metodologia utilizada anteriormente, de modo a aplicá-la para o contexto dos biomas brasileiros e identificar áreas resilientes a mudanças do clima para uma região tropical.



<!-- estudos macroecologicos e macroevolutivos mostrando a importancia topografica e geodiversidade na biodiversidade -->

<!-- biodiversidade é custosa de monitorar, sensoriamento remoto e monitoramento da biodiversidade -->

<!-- Conservar a natureza, não somente a biodiversidade -->

