# Resumo
<!-- Nos nossos textos temos que padronizar o que entendemos por adatação às mudanças climáticas. No sentido mais restrito, adaptação é a mudança evolutiva da espécies em reposta à pressão ambiental, assim as espécies podem se adaptar (evoluir) para terem condições fisiológicas que suportem o novo clima, ou migrarem para áreas adequadas aos seus nichos. No entento, há também adaptação sendo usado em sentidos mais amplos, incluindo a migração. Sugiro mantermos o termo mais restrito, para ficar mais relacionado conceitualmente com a discussão de evolução de nicho e resgate evolutivo --> 

As mudanças no clima modificam ambientes naturais e pressionam espécies a se adaptarem às novas condições ambientais ou alterarem suas distribuições espaciais para locais adequados climaticatimente.
A identificação de locais com adequabilidade climática para sustentar a biodiversidade no futuro de mudanças climáticas é imprescindível para o planejamento sistemático de ações de conservação e restauração.
Nesse sentido, o objetivo principal do projeto é mapear sítios resilientes às mudanças climáticas, que permitam a movimentação da biodiversidade na busca de áreas mais climaticamente adequadas.
O termo _áreas resilientes_ indica locais que apresentam condições necessárias para que espécies e processos ecológicos persistam às mudanças climáticas regionais, definidos por sua alta diversidade microclimática, grau de conservação e conectividade. 
A metodologia proposta para isso combina a diversidade da paisagem, um proxy da variabilidade microclimática, com a conectividade local, identificando locais que forneçam condições microclimáticas para o enfrentamento às mudanças climáticas, cujas matrizes da paisagem sejam permeáveis às movimentação das espécies.
A diversidade da paisagem é baseada na geodiversidade (geomorphologia, geologia, pedologia e hidrologia) do terreno, composta pela variedade de _landforms_, amplitude altitudinal, densidade e quantidade de áreas úmidas e diversidade de solos.
A conectividade local é baseada na resistência das matrizes da paisagem ao movimento da biodiversidade, combinando uso do solo e infraestruturas de energia e transporte existentes (com maior ou menor grau de antropização).
A metodologia desenvolvida segue três premissas básicas: (1) a diversidade de espécies é correlacionada com a diversidade da paisagem (geodiversidade); (2) em um cenário de mudança climática, espécies se beneficiam de microclimas locais para se manterem na paisagem; e (3) populações de espécies podem usar microclimas e acompanhar mudanças microclimáticas se as áreas adequadas forem permeáveis e bem conectadas.
Essa análise foi proposta e validada para a América do Norte pela _The Nature Conservancy_ (TNC), complementando outras metodologias disponíveis na literatura, uma vez que ela foca nas propriedades do terreno para identificar áreas resilientes. 
A aplicação da metodologia da TNC para os biomas brasileiros é um passo importante na identificaçao de sítios resilientes em ambientes tropicais megadiversos. 
Atuando em conjunto com especialistas dos diferentes biomas e baseado na literatura disponível, o projeto busca adequar a metodologia original ao contexto dos biomas brasileiros, refinando e adaptando quando necessário. <!-- Não estamos testando, estamos adequando e desenvolvendo a metodologia  --> 
O produto resultante desse projeto é um mapa de áreas resilientes e conectadas para os biomas do Brasil e permite identificar áreas com potencial de sustentar animais e plantas em um clima sob mudanças, um relatório técnico, uma documentação reproduzível das análises e um artigo científico.

__Palavras chave:__
Resiliência climática, mudanças climáticas, conectividade, paisagem, geodiversidade, conservação, biodiversidade

